TASK: 1
NUM_GPUS: 1
RNG_SEED: 0
CHECKPOINT_DIR: checkpoints/slowfast
LOG_DIR: logs/
LOG_PERIOD: 1
DATA_PATH: '/mnt/md0/yinw/project/data/CATER/max2action/'
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  BLOCK_FUNC: bottleneck_block
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
TRAIN:
  ENABLE: False
  DATASET: cater
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  RESUME: False
  LOAD_PATH: resume/path
TEST:
  ENABLE: True
  DATASET: cater
  BATCH_SIZE: 1
  LOAD_PATH: checkpoints/slowfast/checkpoint_epoch_00000.pth.tar
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [240, 280]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  MEAN: [0.45, 0.45, 0.45]
  STD: [0.225, 0.225, 0.225]
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: cosine
  WARMUP_EPOCH: 20
  MULTI_STEP: [35, 60, 90]
  MAX_EPOCH: 1
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_START_LR: 0.001
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 14
  ARCH: slowfast
  LOSS_FUNC: bce
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
