NUM_GPUS: 1
RNG_SEED: 0
CHECKPOINT_DIR: checkpoints/
LOG_DIR: logs/
LOG_PERIOD: 5
DATA_PATH: 'data path'
TRAIN:
  ENABLE: True
  DATASET: data
  BATCH_SIZE: 8
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 2
  RESUME: False
TEST:
  ENABLE: True
  BATCH_SIZE: 4
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  BLOCK_FUNC: bottleneck_block
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  MEAN: [0.45, 0.45, 0.45]
  STD: [0.225, 0.225, 0.225]
SOLVER:
  BASE_LR: 0.05
  LR_POLICY: cosine
  MULTI_STEP: [30, 60, 90]
  MAX_EPOCH: 60
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCH: 10
  WARMUP_START_LR: 0.001
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 174
  ARCH: slowfast
  LOSS_FUNC: bce
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True